import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <div className='txnsList'>
          <h2>Ethereum</h2>
          <h2 className='walletEthBlock'>Wallet: </h2>
          <h2 className='balanceEthBlock'>Balance: </h2>
          <h3>Transactions:</h3>
          <ul className='txnsList__ul txnsList__ul_eth'></ul>
        </div>

        <div className='txnsList'>
          <h2>Matic (Polygon) </h2>
          <h2 className='walletMaticBlock'>Wallet: </h2>
          <h2 className='balanceMaticBlock'>Balance: </h2>
          <h3>Transactions:</h3>
          <ul className='txnsList__ul txnsList__ul_matic'></ul>
        </div>
      </div>

    </div>
  )
}
